# 人品值区间的回复语（多个回复语用列表表示）
"0-20":
  - "主人，今天运气糟糕，最好不要外出，免得遇到不开心的事情。"
  - "运气差得不可思议，主人，还是待在家里喝杯热茶暖暖身子吧。"
  - "今天的你，注定要遭遇不幸，还是在家陪我玩吧。"
  - "有点小霉运，主人，尽量避免重大决策，免得后悔哦。"
  - "运气不太好，但还不至于糟糕，主人，给我一个抱抱，心情会好点的。"
"20-40":
  - "今天有点小霉运，主人，还是多休息，别太劳累了。"
  - "运气不太好，但还不至于糟糕，主人，来点甜点提提神吧。"
  - "今天虽然不好，但总比0分好，主人，别灰心，明天会更好！"
  - "今天的运气一般，做事可以稍微放心，但也别太大意哦。"
  - "运气平平，没什么大喜大悲的事情，主人，陪我玩会儿游戏吧。"
"40-60":
  - "今天的运气一般，主人，做事可以稍微放心，但也别掉以轻心。"
  - "运气平平，主人，没什么大喜大悲的事情，保持冷静哦。"
  - "今天稍微有点运气，主人，保持冷静，别太得意忘形了。"
  - "今天运气不错，有些事情会顺利进行，记得感谢我哦。"
  - "稍有好运，主人，适合做一些尝试，但也要小心谨慎。"
"60-80":
  - "今天运气不错，有些事情会顺利进行，记得请我吃零食哦。"
  - "稍有好运，主人，适合做一些尝试，但也别太冒险。"
  - "今天运气挺好，做事顺风顺水，主人，快去实现你的愿望吧！"
  - "运气爆棚，做什么都顺利，记得带上我一起分享喜悦。"
  - "运势极佳，能成的事都会顺利，主人，快去实现你的梦想吧！"
"80-100":
  - "今天运气爆棚，做什么都顺利！"
  - "今天的你运气极好，可以尝试一些挑战。"
  - "今天运势极佳，能成的事都会顺利！"
  - "简直是幸运日，什么都顺利，记得给我奖励哦。"
  - "运气好到爆棚，主人，快去买彩票，说不定能中大奖！"